# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: actions/setup-node@v2-beta
      with:
        node-version: '12'
        check-latest: true
    - run: npm install
    - run: npm i @angular/cli
    - run: npm i ionic/cli
    - run: ng update
    - run: ionic serve
